In [1]:
import pandas as pd

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv("netflix_titles.csv")

In [4]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [5]:
df.shape

(8807, 12)

In [6]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [7]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [8]:
df.duplicated().sum()

0

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [10]:
df.describe(include="all")

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
count,8807,8807,8807,6173,7982,7976,8797,8807.000000,8803,8804,8807,8807
unique,8807,2,8807,4528,7692,748,1767,NaN,17,220,514,8775
top,s1,Movie,Dick Johnson Is Dead,Rajiv Chilaka,David Attenborough,United States,"January 1, 2020",NaN,TV-MA,1 Season,"Dramas, International Movies","Paranormal activity at a lush, abandoned prope..."
freq,1,6131,1,19,19,2818,109,NaN,3207,1793,362,4
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014.180198,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.819312,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1925.000000,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013.000000,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017.000000,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019.000000,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021.000000,NaN,NaN,NaN,NaN

In [11]:
df[df["rating"].isnull()]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
5989,s5990,Movie,13TH: A Conversation with Oprah Winfrey & Ava ...,NaN,"Oprah Winfrey, Ava DuVernay",NaN,"January 26, 2017",2017,NaN,37 min,Movies,Oprah Winfrey sits down with director Ava DuVe...
6827,s6828,TV Show,Gargantia on the Verdurous Planet,NaN,"Kaito Ishikawa, Hisako Kanemoto, Ai Kayano, Ka...",Japan,"December 1, 2016",2013,NaN,1 Season,"Anime Series, International TV Shows","After falling through a wormhole, a space-dwel..."
7312,s7313,TV Show,Little Lunch,NaN,"Flynn Curry, Olivia Deeble, Madison Lu, Oisín ...",Australia,"February 1, 2018",2015,NaN,1 Season,"Kids' TV, TV Comedies","Adopting a child's perspective, this show take..."
7537,s7538,Movie,My Honor Was Loyalty,Alessandro Pepe,"Leone Frisa, Paolo Vaccarino, Francesco Miglio...",Italy,"March 1, 2017",2015,NaN,115 min,Dramas,"Amid the chaos and horror of World War II, a c..."

In [12]:
df["rating"].value_counts(dropna=False)

rating
TV-MA       3207
TV-14       2160
TV-PG        863
R            799
PG-13        490
TV-Y7        334
TV-Y         307
PG           287
TV-G         220
NR            80
G             41
TV-Y7-FV       6
NaN            4
NC-17          3
UR             3
74 min         1
84 min         1
66 min         1
Name: count, dtype: int64

In [13]:
df[df["rating"].str.contains("min", na=False)]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
5541,s5542,Movie,Louis C.K. 2017,Louis C.K.,Louis C.K.,United States,"April 4, 2017",2017,74 min,NaN,Movies,"Louis C.K. muses on religion, eternal love, gi..."
5794,s5795,Movie,Louis C.K.: Hilarious,Louis C.K.,Louis C.K.,United States,"September 16, 2016",2010,84 min,NaN,Movies,Emmy-winning comedy writer Louis C.K. brings h...
5813,s5814,Movie,Louis C.K.: Live at the Comedy Store,Louis C.K.,Louis C.K.,United States,"August 15, 2016",2015,66 min,NaN,Movies,The comic puts his trademark hilarious/thought...

In [14]:
df[df["rating"].str.contains("min", na=False)][["show_id", "title", "type", "rating", "duration"]]

     show_id                                 title   type  rating duration
5541   s5542                       Louis C.K. 2017  Movie  74 min      NaN
5794   s5795                 Louis C.K.: Hilarious  Movie  84 min      NaN
5813   s5814  Louis C.K.: Live at the Comedy Store  Movie  66 min      NaN

In [15]:
df["rating"].unique()

array(['PG-13', 'TV-MA', 'PG', 'TV-14', 'TV-PG', 'TV-Y', 'TV-Y7', 'R',
       'TV-G', 'G', 'NC-17', '74 min', '84 min', '66 min', 'NR', nan,
       'TV-Y7-FV', 'UR'], dtype=object)

In [16]:
df.loc[df["rating"].str.contains("min", na=False), "duration"] = df["rating"]
df.loc[df["rating"].str.contains("min", na=False), "rating"] = np.nan

In [17]:
df["rating"].value_counts(dropna=False)

rating
TV-MA       3207
TV-14       2160
TV-PG        863
R            799
PG-13        490
TV-Y7        334
TV-Y         307
PG           287
TV-G         220
NR            80
G             41
NaN            7
TV-Y7-FV       6
NC-17          3
UR             3
Name: count, dtype: int64

In [18]:
df["duration"].value_counts(dropna=False).head(20)

duration
1 Season     1793
2 Seasons     425
3 Seasons     199
90 min        152
94 min        146
97 min        146
93 min        146
91 min        144
95 min        137
96 min        130
92 min        129
102 min       122
98 min        120
99 min        118
101 min       116
88 min        116
103 min       114
106 min       111
100 min       108
89 min        106
Name: count, dtype: int64

In [19]:
df[df["duration"].isnull()][["show_id", "title", "type", "rating", "duration"]]

Empty DataFrame
Columns: [show_id, title, type, rating, duration]
Index: []

In [20]:
df[df["rating"].str.contains("min", na=False)]

Empty DataFrame
Columns: [show_id, type, title, director, cast, country, date_added, release_year, rating, duration, listed_in, description]
Index: []

In [21]:
df["show_id"].isnull().sum()

0

In [22]:
df["show_id"].duplicated().sum()

0

In [24]:
df["show_id"].head()

0    s1
1    s2
2    s3
3    s4
4    s5
Name: show_id, dtype: object

In [25]:
df["show_id"].tail()

8802    s8803
8803    s8804
8804    s8805
8805    s8806
8806    s8807
Name: show_id, dtype: object

In [26]:
df["type"].isnull().sum()

0

In [27]:
df["type"].value_counts(dropna=False)

type
Movie      6131
TV Show    2676
Name: count, dtype: int64

In [28]:
df["type"].unique()

array(['Movie', 'TV Show'], dtype=object)

In [29]:
df["title"].isnull().sum()

0

In [30]:
df["title"].duplicated().sum()

0

In [31]:
df["title"].unique()[:20]

array(['Dick Johnson Is Dead', 'Blood & Water', 'Ganglands',
       'Jailbirds New Orleans', 'Kota Factory', 'Midnight Mass',
       'My Little Pony: A New Generation', 'Sankofa',
       'The Great British Baking Show', 'The Starling',
       'Vendetta: Truth, Lies and The Mafia', 'Bangkok Breaking',
       'Je Suis Karl', 'Confessions of an Invisible Girl',
       'Crime Stories: India Detectives', 'Dear White People',
       "Europe's Most Dangerous Man: Otto Skorzeny in Spain",
       'Falsa identidad', 'Intrusion', 'Jaguar'], dtype=object)

In [33]:
df["director"].isnull().sum()

2634

In [35]:
df["director"].duplicated().sum()

4278

In [36]:
df["director"].unique()[:20]

array(['Kirsten Johnson', nan, 'Julien Leclercq', 'Mike Flanagan',
       'Robert Cullen, José Luis Ucha', 'Haile Gerima', 'Andy Devonshire',
       'Theodore Melfi', 'Kongkiat Komesiri', 'Christian Schwochow',
       'Bruno Garotti', 'Pedro de Echave García, Pablo Azorín Williams',
       'Adam Salky', 'Olivier Megaton', 'K.S. Ravikumar',
       'Alex Woo, Stanley Moore', 'S. Shankar', 'Rajiv Menon',
       'Dennis Dugan', 'Scott Stewart'], dtype=object)

In [38]:
df["director"]=df["director"].fillna("Unknown")

In [39]:
df["director"].isnull().sum()

0

In [40]:
df["director"].value_counts().head()

director
Unknown                   2634
Rajiv Chilaka               19
Raúl Campos, Jan Suter      18
Suhas Kadav                 16
Marcus Raboy                16
Name: count, dtype: int64

In [41]:
df["cast"].isnull().sum()

825

In [42]:
df["cast"].duplicated().sum()

1114

In [43]:
df["cast"].unique()[:20]

array([nan,
       'Ama Qamata, Khosi Ngema, Gail Mabalane, Thabang Molaba, Dillon Windvogel, Natasha Thahane, Arno Greeff, Xolile Tshabalala, Getmore Sithole, Cindy Mahlangu, Ryle De Morny, Greteli Fincham, Sello Maake Ka-Ncube, Odwa Gwanya, Mekaila Mathys, Sandi Schultz, Duane Williams, Shamilla Miller, Patrick Mofokeng',
       'Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabiha Akkari, Sofia Lesaffre, Salim Kechiouche, Noureddine Farihi, Geert Van Rampelberg, Bakary Diombera',
       'Mayur More, Jitendra Kumar, Ranjan Raj, Alam Khan, Ahsaas Channa, Revathi Pillai, Urvi Singh, Arun Kumar',
       'Kate Siegel, Zach Gilford, Hamish Linklater, Henry Thomas, Kristin Lehman, Samantha Sloyan, Igby Rigney, Rahul Kohli, Annarah Cymone, Annabeth Gish, Alex Essoe, Rahul Abburi, Matt Biedel, Michael Trucco, Crystal Balint, Louis Oliver',
       'Vanessa Hudgens, Kimiko Glenn, James Marsden, Sofia Carson, Liza Koshy, Ken Jeong, Elizabeth Perkins, Jane Krakowski, Michael McKean, Phil LaMarr',
       'Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra Duah, Nick Medley, Mutabaruka, Afemo Omilami, Reggie Carter, Mzuri',
       'Mel Giedroyc, Sue Perkins, Mary Berry, Paul Hollywood',
       "Melissa McCarthy, Chris O'Dowd, Kevin Kline, Timothy Olyphant, Daveed Diggs, Skyler Gisondo, Laura Harrier, Rosalind Chao, Kimberly Quinn, Loretta Devine, Ravi Kapoor",
       'Sukollawat Kanarot, Sushar Manaying, Pavarit Mongkolpisit, Sahajak Boonthanakit, Suthipongse Thatphithakkul, Bhasaworn Bawronkirati, Daweerit Chullasapya, Waratthaya Wongchayaporn, Kittiphoom Wongpentak, Abhicha Thanachanun, Nophand Boonyai, Kittipong Khamsat, Arisara Wongchalee, Jaytiya Naiwattanakul, Pantipa Arunwattanachai, Panupan Jantanawong, Kungtap Saelim, Phumphat Chartsuriyakiat, Issara Veranitinunt, Keerati Sivakuae, Panjai Sirisuwan, Supranee Charoenpol, Suda Chuenban, Visaka Banhansupavat, Pitchatorn Santinatornkul',
       'Luna Wedler, Jannis Niewöhner, Milan Peschel, Edin Hasanović, Anna Fialová, Marlon Boess, Victor Boccard, Fleur Geffrier, Aziz Dyab, Mélanie Fouché, Elizaveta Maximová',
       'Klara Castanho, Lucca Picon, Júlia Gomes, Marcus Bessa, Kiria Malheiros, Fernanda Concon, Gabriel Lima, Caio Cabral, Leonardo Cidade, Jade Cardozo',
       'Logan Browning, Brandon P. Bell, DeRon Horton, Antoinette Robertson, John Patrick Amedori, Ashley Blaine Featherson, Marque Richardson, Giancarlo Esposito',
       'Luis Ernesto Franco, Camila Sodi, Sergio Goyri, Samadhi Zendejas, Eduardo Yáñez, Sonya Smith, Alejandro Camacho, Azela Robinson, Uriel del Toro, Géraldine Bazán, Gabriela Roel, Marcus Ornellas',
       'Freida Pinto, Logan Marshall-Green, Robert John Burke, Megan Elisabeth Kelly, Sarah Minnich, Hayes Hargrove, Mark Sivertsen, Brandon Fierro, Antonio Valles, Clint Obenchain',
       'Blanca Suárez, Iván Marcos, Óscar Casas, Adrián Lastra, Francesc Garrido, Stefan Weinert, Julia Möller, Alicia Chojnowski',
       'Engin Altan Düzyatan, Serdar Gökhan, Hülya Darcan, Kaan Taşaner, Esra Bilgiç, Osman Soykut, Serdar Deniz, Cengiz Coşkun, Reshad Strik, Hande Subaşı',
       'Kamal Hassan, Meena, Gemini Ganesan, Heera Rajgopal, Nassar, S.P. Balasubrahmanyam',
       'Maisie Benson, Paul Killam, Kerry Gudjohnsen, AC Lim',
       'Prashanth, Aishwarya Rai Bachchan, Sri Lakshmi, Nassar'],
      dtype=object)

In [44]:
df["cast"]=df["cast"].fillna("Unknown")

In [45]:
df["cast"].isnull().sum()

0

In [46]:
df["country"].isnull().sum()

831

In [47]:
df["country"].duplicated().sum()

8058

In [49]:
df["country"].unique()[:30]

array(['United States', 'South Africa', nan, 'India',
       'United States, Ghana, Burkina Faso, United Kingdom, Germany, Ethiopia',
       'United Kingdom', 'Germany, Czech Republic', 'Mexico', 'Turkey',
       'Australia', 'United States, India, France', 'Finland',
       'China, Canada, United States',
       'South Africa, United States, Japan', 'Nigeria', 'Japan',
       'Spain, United States', 'France', 'Belgium',
       'United Kingdom, United States', 'United States, United Kingdom',
       'France, United States', 'South Korea', 'Spain',
       'United States, Singapore', 'United Kingdom, Australia, France',
       'United Kingdom, Australia, France, United States',
       'United States, Canada', 'Germany, United States',
       'South Africa, United States'], dtype=object)

In [50]:
df["country"]=df["country"].fillna("Unknown")

In [52]:
df["country"].isnull().sum()

0

In [53]:
df["country"].value_counts().head(10)

country
United States     2818
India              972
Unknown            831
United Kingdom     419
Japan              245
South Korea        199
Canada             181
Spain              145
France             124
Mexico             110
Name: count, dtype: int64

In [54]:
df["country"].str.strip().equals(df["country"])

True

In [55]:
df["date_added"].isnull().sum()

10

In [56]:
df[df["date_added"].isnull()][["show_id","title","type","date_added"]]

     show_id                                        title     type date_added
6066   s6067  A Young Doctor's Notebook and Other Stories  TV Show        NaN
6174   s6175              Anthony Bourdain: Parts Unknown  TV Show        NaN
6795   s6796                                      Frasier  TV Show        NaN
6806   s6807                                      Friends  TV Show        NaN
6901   s6902                              Gunslinger Girl  TV Show        NaN
7196   s7197                                     Kikoriki  TV Show        NaN
7254   s7255                          La Familia P. Luche  TV Show        NaN
7406   s7407                                        Maron  TV Show        NaN
7847   s7848                                 Red vs. Blue  TV Show        NaN
8182   s8183                 The Adventures of Figaro Pho  TV Show        NaN

In [57]:
df["date_added"].dropna().head(10)

0    September 25, 2021
1    September 24, 2021
2    September 24, 2021
3    September 24, 2021
4    September 24, 2021
5    September 24, 2021
6    September 24, 2021
7    September 24, 2021
8    September 24, 2021
9    September 24, 2021
Name: date_added, dtype: object

In [58]:
df["date_added"]=pd.to_datetime(df["date_added"])

ValueError: time data " August 4, 2017" doesn't match format "%B %d, %Y", at position 1442. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [59]:
df["date_added"] = pd.to_datetime(
    df["date_added"],
    format="%B %d, %Y",
    errors="coerce"
)

In [60]:
df["date_added"].isnull().sum()

98

In [61]:
df["date_added"].head(10)

0   2021-09-25
1   2021-09-24
2   2021-09-24
3   2021-09-24
4   2021-09-24
5   2021-09-24
6   2021-09-24
7   2021-09-24
8   2021-09-24
9   2021-09-24
Name: date_added, dtype: datetime64[ns]

In [62]:
df["year_added"] = df["date_added"].dt.year
df["month_added"] = df["date_added"].dt.month
df["month_name"] = df["date_added"].dt.month_name()

In [63]:
df[["date_added", "year_added", "month_added", "month_name"]].head(10)

  date_added  year_added  month_added month_name
0 2021-09-25      2021.0          9.0  September
1 2021-09-24      2021.0          9.0  September
2 2021-09-24      2021.0          9.0  September
3 2021-09-24      2021.0          9.0  September
4 2021-09-24      2021.0          9.0  September
5 2021-09-24      2021.0          9.0  September
6 2021-09-24      2021.0          9.0  September
7 2021-09-24      2021.0          9.0  September
8 2021-09-24      2021.0          9.0  September
9 2021-09-24      2021.0          9.0  September

In [64]:
df[["year_added", "month_added", "month_name"]].isnull().sum()

year_added     98
month_added    98
month_name     98
dtype: int64

In [65]:
df["rating"].isnull().sum()

7

In [66]:
df["rating"].value_counts(dropna=False)

rating
TV-MA       3207
TV-14       2160
TV-PG        863
R            799
PG-13        490
TV-Y7        334
TV-Y         307
PG           287
TV-G         220
NR            80
G             41
NaN            7
TV-Y7-FV       6
NC-17          3
UR             3
Name: count, dtype: int64

In [67]:
df["rating"] = df["rating"].fillna("Unknown")

In [68]:
df["rating"].isnull().sum()

0

In [69]:
df["rating"].value_counts().head(15)

rating
TV-MA       3207
TV-14       2160
TV-PG        863
R            799
PG-13        490
TV-Y7        334
TV-Y         307
PG           287
TV-G         220
NR            80
G             41
Unknown        7
TV-Y7-FV       6
NC-17          3
UR             3
Name: count, dtype: int64

In [70]:
df["duration"].isnull().sum()

0

In [71]:
df["duration"].value_counts(dropna=False).head(20)

duration
1 Season     1793
2 Seasons     425
3 Seasons     199
90 min        152
94 min        146
97 min        146
93 min        146
91 min        144
95 min        137
96 min        130
92 min        129
102 min       122
98 min        120
99 min        118
101 min       116
88 min        116
103 min       114
106 min       111
100 min       108
89 min        106
Name: count, dtype: int64

In [72]:
df[df["duration"].isnull()][["show_id", "title", "type", "duration"]]

Empty DataFrame
Columns: [show_id, title, type, duration]
Index: []

In [73]:
df["duration_value"] = df["duration"].str.extract(r"(\d+)").astype(int)

df["duration_unit"] = df["duration"].str.extract(r"([A-Za-z]+)")

In [74]:
df[["duration", "duration_value", "duration_unit"]].head(10)

    duration  duration_value duration_unit
0     90 min              90           min
1  2 Seasons               2       Seasons
2   1 Season               1        Season
3   1 Season               1        Season
4  2 Seasons               2       Seasons
5   1 Season               1        Season
6     91 min              91           min
7    125 min             125           min
8  9 Seasons               9       Seasons
9    104 min             104           min

In [75]:
df[["duration_value", "duration_unit"]].isnull().sum()

duration_value    0
duration_unit     0
dtype: int64

In [76]:
df["duration_unit"].value_counts()

duration_unit
min        6131
Season     1793
Seasons     883
Name: count, dtype: int64

In [77]:
df["duration_unit"] = df["duration_unit"].replace({
    "Season": "Seasons"
})

In [78]:
df["duration_unit"].value_counts()

duration_unit
min        6131
Seasons    2676
Name: count, dtype: int64

In [79]:
df["listed_in"].isnull().sum()

0

In [80]:
df["listed_in"].value_counts().head(15)

listed_in
Dramas, International Movies                        362
Documentaries                                       359
Stand-Up Comedy                                     334
Comedies, Dramas, International Movies              274
Dramas, Independent Movies, International Movies    252
Kids' TV                                            220
Children & Family Movies                            215
Children & Family Movies, Comedies                  201
Documentaries, International Movies                 186
Dramas, International Movies, Romantic Movies       180
Comedies, International Movies                      176
Comedies, International Movies, Romantic Movies     152
Dramas                                              138
Dramas, International Movies, Thrillers             134
Action & Adventure, Dramas, International Movies    132
Name: count, dtype: int64

In [81]:
df["listed_in"].head(10)

0                                        Documentaries
1      International TV Shows, TV Dramas, TV Mysteries
2    Crime TV Shows, International TV Shows, TV Act...
3                               Docuseries, Reality TV
4    International TV Shows, Romantic TV Shows, TV ...
5                   TV Dramas, TV Horror, TV Mysteries
6                             Children & Family Movies
7     Dramas, Independent Movies, International Movies
8                         British TV Shows, Reality TV
9                                     Comedies, Dramas
Name: listed_in, dtype: object

In [82]:
genre_df = df[["show_id", "listed_in"]].copy()

genre_df["genre"] = genre_df["listed_in"].str.split(",")

genre_df = genre_df.explode("genre")

genre_df["genre"] = genre_df["genre"].str.strip()

In [83]:
genre_df.head(15)

,show_id,listed_in,genre
0,s1,Documentaries,Documentaries
1,s2,"International TV Shows, TV Dramas, TV Mysteries",International TV Shows
1,s2,"International TV Shows, TV Dramas, TV Mysteries",TV Dramas
1,s2,"International TV Shows, TV Dramas, TV Mysteries",TV Mysteries
2,s3,"Crime TV Shows, International TV Shows, TV Act...",Crime TV Shows
2,s3,"Crime TV Shows, International TV Shows, TV Act...",International TV Shows
2,s3,"Crime TV Shows, International TV Shows, TV Act...",TV Action & Adventure
3,s4,"Docuseries, Reality TV",Docuseries
3,s4,"Docuseries, Reality TV",Reality TV
4,s5,"International TV Shows, Romantic TV Shows, TV ...",International TV Shows
4,s5,"International TV Shows, Romantic TV Shows, TV ...",Romantic TV Shows
4,s5,"International TV Shows, Romantic TV Shows, TV ...",TV Comedies
5,s6,"TV Dramas, TV Horror, TV Mysteries",TV Dramas
5,s6,"TV Dramas, TV Horror, TV Mysteries",TV Horror
5,s6,"TV Dramas, TV Horror, TV Mysteries",TV Mysteries

In [84]:
genre_df["genre"].value_counts().head(15)

genre
International Movies        2752
Dramas                      2427
Comedies                    1674
International TV Shows      1351
Documentaries                869
Action & Adventure           859
TV Dramas                    763
Independent Movies           756
Children & Family Movies     641
Romantic Movies              616
TV Comedies                  581
Thrillers                    577
Crime TV Shows               470
Kids' TV                     451
Docuseries                   395
Name: count, dtype: int64

In [85]:
genre_df.head(15)

,show_id,listed_in,genre
0,s1,Documentaries,Documentaries
1,s2,"International TV Shows, TV Dramas, TV Mysteries",International TV Shows
1,s2,"International TV Shows, TV Dramas, TV Mysteries",TV Dramas
1,s2,"International TV Shows, TV Dramas, TV Mysteries",TV Mysteries
2,s3,"Crime TV Shows, International TV Shows, TV Act...",Crime TV Shows
2,s3,"Crime TV Shows, International TV Shows, TV Act...",International TV Shows
2,s3,"Crime TV Shows, International TV Shows, TV Act...",TV Action & Adventure
3,s4,"Docuseries, Reality TV",Docuseries
3,s4,"Docuseries, Reality TV",Reality TV
4,s5,"International TV Shows, Romantic TV Shows, TV ...",International TV Shows
4,s5,"International TV Shows, Romantic TV Shows, TV ...",Romantic TV Shows
4,s5,"International TV Shows, Romantic TV Shows, TV ...",TV Comedies
5,s6,"TV Dramas, TV Horror, TV Mysteries",TV Dramas
5,s6,"TV Dramas, TV Horror, TV Mysteries",TV Horror
5,s6,"TV Dramas, TV Horror, TV Mysteries",TV Mysteries

In [86]:
genre_df.shape

(19323, 3)

In [87]:
genre_df.isnull().sum()

show_id      0
listed_in    0
genre        0
dtype: int64

In [88]:
genre_df.head(10)

,show_id,listed_in,genre
0,s1,Documentaries,Documentaries
1,s2,"International TV Shows, TV Dramas, TV Mysteries",International TV Shows
1,s2,"International TV Shows, TV Dramas, TV Mysteries",TV Dramas
1,s2,"International TV Shows, TV Dramas, TV Mysteries",TV Mysteries
2,s3,"Crime TV Shows, International TV Shows, TV Act...",Crime TV Shows
2,s3,"Crime TV Shows, International TV Shows, TV Act...",International TV Shows
2,s3,"Crime TV Shows, International TV Shows, TV Act...",TV Action & Adventure
3,s4,"Docuseries, Reality TV",Docuseries
3,s4,"Docuseries, Reality TV",Reality TV
4,s5,"International TV Shows, Romantic TV Shows, TV ...",International TV Shows

In [89]:
genre_df = genre_df.drop(columns=["listed_in"])

In [90]:
genre_df.head()

  show_id                   genre
0      s1           Documentaries
1      s2  International TV Shows
1      s2               TV Dramas
1      s2            TV Mysteries
2      s3          Crime TV Shows

In [91]:
genre_df.shape

(19323, 2)

In [92]:
genre_df.duplicated().sum()

0

In [93]:
genre_df[genre_df.duplicated()].head()

Empty DataFrame
Columns: [show_id, genre]
Index: []

In [94]:
df.shape

(8807, 17)

In [95]:
df.isnull().sum()

show_id            0
type               0
title              0
director           0
cast               0
country            0
date_added        98
release_year       0
rating             0
duration           0
listed_in          0
description        0
year_added        98
month_added       98
month_name        98
duration_value     0
duration_unit      0
dtype: int64

In [96]:
df.duplicated().sum()

0

In [98]:
df.dtypes

show_id                   object
type                      object
title                     object
director                  object
cast                      object
country                   object
date_added        datetime64[ns]
release_year               int64
rating                    object
duration                  object
listed_in                 object
description               object
year_added               float64
month_added              float64
month_name                object
duration_value             int32
duration_unit             object
dtype: object

In [99]:
df["show_id"].nunique()

8807

In [100]:
df["show_id"].duplicated().sum()

0

In [101]:
df.to_csv("netflix_cleaned.csv",index=False)

In [102]:
genre_df.to_csv("netflix_genres.csv",index=False)

In [103]:
import pandas as pd

df = pd.read_csv("netflix_cleaned.csv")

df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year_added,month_added,month_name,duration_value,duration_unit
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Unknown,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",2021.0,9.0,September,90,min
1,s2,TV Show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2021.0,9.0,September,2,Seasons
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,2021.0,9.0,September,1,Seasons
3,s4,TV Show,Jailbirds New Orleans,Unknown,Unknown,Unknown,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2021.0,9.0,September,1,Seasons
4,s5,TV Show,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,2021.0,9.0,September,2,Seasons

In [104]:
df.shape

(8807, 17)

In [105]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description',
       'year_added', 'month_added', 'month_name', 'duration_value',
       'duration_unit'],
      dtype='object')